module.exports = {
    customerInsert : `insert into non_ferrousmetals set ?`,
    customerlist : `select * from non_ferrousmetals`,
    customerInsert_a : `insert into alumin set ?`,
    customerInsert_l : `insert into lead_ set ?`,
    customerInsert_z : `insert into zinc set ?`,
    customerInsert_c : `insert into copper set ?`,
    customerInsert_t : `insert into tin set ?`,
    customerInsert_n : `insert into nickel set ?`,
    board_List: `select * from gasipan`,
    board_Insert: `insert into gasipan set ?`,
    truncate: `truncate news`,
    newsList: `select * from news`, 
    newsInsert: `insert into news set ?`,
    statistics: 'select * from result',
    customerlist_a : `select * from alumin `,
    customerlist_l : `select * from lead_ `,
    customerlist_z : `select * from zinc `,
    customerlist_c : `select * from copper `,
    customerlist_t : `select * from tin `,
    customerlist_n : `select * from nickel `,
    dele_non1 : `TRUNCATE non_ferrousmetals`,
    dele_non2 : `TRUNCATE alumin`,
    dele_non3 : `TRUNCATE lead_`,
    dele_non4 : `TRUNCATE tin`,
    dele_non5 : `TRUNCATE zinc`,
    dele_non6 : `TRUNCATE copper`,
    dele_non7 : `TRUNCATE nickel`
}